### PR TITLE
Don't create repository instance in constructor to prevent endless loop

### PR DESCRIPTION
**Pull request by wazum**
This was the only way I could solve this right now.
I tried to replace `EntityManagerInterface` with `ManagerRegistry` but that keeps the same problem (`getRepository` calls `getClassMetadata` and this leads to the endless loop).

### CODE REVIEW

**Comment by benr77** [comment]
This looks like a sensible approach. No work should be done in the constructor as a general rule, and I don't see any drawback on these changes.

Can I ask how you discovered the endless loop? It's not something I've seen yet.

**Comment by wazum** [comment]
That happened after an update to a more recent Doctrine version.

**Comment by benr77** [comment]
OK great. Thanks for the SF6 and PHP8.1 support that's been on my todo list for a long time.

Is this ready to merge now?

**Comment by wazum** [comment]
I removed the changes for Symfony 6 and PHP 8.1 again (will do that in another branch),
I found some problems with serializer normalizing objects (missing dependency on symfony/property-access) and I don't really have any experience with the travis-ci tests, I'll have to check that out first.
The rest should be fine.

**Review by benr77 — APPROVED** [review]

**Comment by benr77** [comment]
> I don't really have any experience with the travis-ci tests, I'll have to check that out first.

Don't worry about Travis - we really should use Github Actions instead.

**Pull request merged**
